### ISSUE TITLE
Join saas-errortracking repository

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#100]
All services deployed as part of OSIO (including Sentry) have their "deployment" repositories. We will have to create one following the process of [`saasherder`](https://github.com/openshiftio/saasherder)

**UPDATE**
Based on the conversation with @aslakknutsen and  @kbsingh we should make our new home part of "errortracking" project, so we need to move our templates to https://github.com/openshiftio/saas-errortracking repository.

**Comment by MatousJobanek** [comment]
Before I do the PR to the `saas-errortracking` repo I need to finish one task:

- [ ] tag the images so we can support the "latest" tag 

and clarify one thing:
* the registry we want to push/pull the images to/from. There are two options:
  * `push.registry.devshift.net` - supported by centos-ci environment
    * the deployment could be automated by centos-ci deploy job (credentials are stored there)
  * `docker.io`
    * to make it automated by centos-ci we would need to somehow provide the credentials there. Or do it manually

based on the decision, I'll need to potentionally also add the `cico-deploy.sh` script to our project and send a PR to `openshiftio-cico-jobs` repo

**Comment by bartoszmajsak** [comment]
I am not sure if we need `latest` - it's a moving target and we don't know what exact version is running on prod until we extract it from somewhere. Unless it's needed by the cico automation process I would stick with version tags (as we do now).

**Comment by bartoszmajsak** [comment]
As for the registry I think we should be pushing to devshift, especially when using centos and soon RHEL.

Docker hub could be nice for streamlined upstream images, so I think we will come back to the discussion about pushing there later on anyway.

**Comment by MatousJobanek** [comment]
as for the latest. there are two reasons to do that:
1. it is one of the "required" steps for the cico build process
2. we would need to change the parameter in `saas-errortracking` config file for every update of the docker image (change of the version tag).

as for the registry - yeah, I was kind of expecting that the devshift is the correct one, but wasn't 100% sure

**Comment by bartoszmajsak** [comment]
Ok, then the process needs that. We have version info exposed anyway and saasherder tracks it by commit hashes, so I think we are good.

**Comment by MatousJobanek** [comment]
Both the devshift thingy and the latest tags are part of: https://github.com/arquillian/ike-prow-plugins/pull/132

**Comment by MatousJobanek** [comment]
The [PR](https://github.com/openshiftio/saas-errortracking/pull/6) that adds `ike-prow-plugins` services to the `saas-errortracking` repository has been merged here: https://github.com/openshiftio/saas-errortracking/commit/d1b8e2ab52df82daa112a67b662bc5ea745424c7
