### ISSUE TITLE
Metrics collection

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#101]
### Infrastructure metrics

- goroutines
- gc pause
- gc count
- memory allocations
- memory frees
- ....

### Service metrics

- rate limits
- incoming webhooks
- handled events
- ....

#### Test keeper
- /ok-without-tests vs size of the PR
- PRs with and without tests
- ....

**Comment by bartoszmajsak** [comment]
### PCP

https://github.com/fabric8-services/fabric8-notification/blob/2358e9e9cbf9be6728a5a08106533c35dd16b8f2/pcp.repo

https://github.com/fabric8-services/fabric8-notification/blob/2358e9e9cbf9be6728a5a08106533c35dd16b8f2/notification%2Bpmcd.sh

### Prometheus

Adding Prometheus to our code could be done in a similar fashion as in other OSIO golang services:

https://github.com/fabric8-services/fabric8-notification/blob/2358e9e9cbf9be6728a5a08106533c35dd16b8f2/main.go#L149-L162

then in PCP config

https://github.com/fabric8-services/fabric8-notification/blob/2358e9e9cbf9be6728a5a08106533c35dd16b8f2/notification%2Bpmcd.sh#L38

**Comment by bartoszmajsak** [comment]
### Custom metrics

https://github.com/fabric8-services/fabric8-wit/blob/master/metric/

**Comment by bartoszmajsak** [comment]
Lets use this issue to also discuss other metrics we would like to gather.

**Comment by dipak-pawar** [comment]
Next Steps:
 **Service Metrics**
- [ ] rate limits
- [ ] incoming webhooks
- [ ] handled events

**Plugin metrics**
- Test Keeper
 - [ ] /ok-without-tests vs size of the PR
 - [ ] PRs with and without tests

**Comment by dipak-pawar** [comment]
@bartoszmajsak I don't see how can I implement  x `vs` y graph in prometheus metrics [types](https://prometheus.io/docs/concepts/metric_types/). For Test Keeper metrics (/ok-without-tests vs size of the PR, PRs with and without tests) . Do you want me to implement it as counter/gauge/histogram metrics?

I hope I am not missing anything?

**Comment by MatousJobanek** [comment]
Hi @dipak-pawar,
if I'm not mistaken, the main point in test-keeper metrics was to measure the quality of the PRs. How many times was provided a PR with/without tests, so the `/ok-without-tests` command had to be used.
When there was a PR without tests, then how big it was - one file or twenty files...
In other words, try to measure the quality of the PRs and what is the impact of our plugins on making the quality better.
As for your question - maybe gauge would be the best, but it really depends on the result that you get from premetheus - you can try it on minishift after all.

**Comment by MatousJobanek** [comment]
I'm closing this epic issue as all sub-issues are done
