### ISSUE TITLE
New home for configuration files

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#119]
To simplify configuration management both from our perspective and end-users we should move configuration to one place - `.ike-prow/`.

This change requires following adjustments

- [x] change default location of the plugin to `.ike-prow/plugin-name.[yml|yaml]`
- [x] similar for plugin hint (convention over configuration as discussed here https://github.com/arquillian/ike-prow-plugins/pull/84#discussion_r179571129)
- [x] add this folder to default exclusions https://github.com/arquillian/ike-prow-plugins/blob/69435eb3bbd5135ee2ceed6c7a36a7d8859f4e72/pkg/assets/config/test-keeper.yaml#L131

**Comment by bartoszmajsak** [comment]
Apart of the repository which @gastaldi linked, here are the other ones which we should open PR to with the new location of the config:

- [fabric8-wit](https://github.com/fabric8-services/fabric8-wit/pull/2011)
- https://github.com/fabric8-services/fabric8-auth

Please also review if their settings are not overlapping with our extended defaults. In such case, we can maybe even get rid of the files in the repos (like we can in `auth`).

**Comment by dipak-pawar** [comment]
@bartoszmajsak I have gone through [fabric8-auth](https://github.com/fabric8-services/fabric8-auth),  [fabric8-wit](https://github.com/fabric8-services/fabric8-wit), Looks like we can get rid of the file `test-keeper.yaml` in both the repositories as our extended defaults are covering all expressions which is present in both repositories.  I will submit a PR once this get merged.
