### ISSUE TITLE
Create project with the same name as DOCKER_REPO variable

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/ike-prow-plugins#124]
Currently, we have `oc-init-project` goal defined in [Makefile](https://github.com/arquillian/ike-prow-plugins/blob/master/Makefile#L115#L117) which is generating project by name`ike-pro-plugins`, but in the [Makefile](https://github.com/arquillian/ike-prow-plugins/blob/master/Makefile#L12) we are assinging `DOCKER_REPO?=arquillian` due to which the built image is like `docker-registry-default.192.168.99.100.nip.io/arquillian/hook`, 

but as we don't have project with name `arquillian`(we have project by name `ike-pro-plugins`) you can't push it to local minishift registry.

Whereas if I created project by `arquillian` manually I was able to sucessfully push new built image to minishift local registry

**Comment by dipak-pawar** [comment]
@bartoszmajsak, @MatousJobanek 

We have two options here
1. Rename `PROJECT_NAME` to `arquillian`
2. Raname `DOCKER_REPO` to `ike-prow-plugins`

to resolve local minishift container registry push

**Comment by bartoszmajsak** [comment]
Those two variables can be overwritten (hence `?=`), everything that you need for local minishift development is in [`local.sh`](https://github.com/arquillian/ike-prow-plugins/blob/master/local.sh) 

Is it missing in the official docs?

**Comment by dipak-pawar** [comment]
@bartosz: With official setup and using `local.sh` works. But wouldn't be a good if we use the same names while pushing to local minishift registry and `docker.io`?

**Comment by bartoszmajsak** [comment]
We have `arquillian` org in `docker.io` and that's where I am pushing the images to deployed in OSIO. As a project name for OS it does not make much sense in my opinion. Thus I created `local.sh` and make those variables configurable - so you have everything automated and seamless.

However, unifying repo name to be the same as project name makes perfect sense - feel free to open PR with this improvement.
