### ISSUE TITLE
Liveliness and readiness probes for the hook service

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#129]
Similarly to #62 we should have probes for the hook service. As this is an external dependency we have few options to consider here:

- call existing `hook` endpoint (e.g. hook with the proper webhook payload hashed with our secret - see the [details here](https://developer.github.com/webhooks/#delivery-headers) - you can take test github webhook payload for example, you can trigger that from the webhook configuration page)
- script some CLI check to check go process is running

I would try the first approach as it will give us better insight if the service is up and running properly

**Comment by MatousJobanek** [comment]
Closed via https://github.com/arquillian/ike-prow-plugins/pull/137
