### ISSUE TITLE
Document process how to configure ike-prow-plugins for a repository

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/ike-prow-plugins#156]
Currently we have process to enable prow plugin for there repository documented in our guide. http://arquillian.org/ike-prow-plugins/#_configuration.

It'll be helpful for user if we document end to end step for enabling plugin for there repository in housekeeping repo.

**Comment by hemanik** [comment]
Related: https://github.com/arquillian/ike-prow-plugins/issues/59

**Comment by MatousJobanek** [comment]
Related issue https://gitlab.cee.redhat.com/dtsd/devguide/issues/6

**Comment by dipak-pawar** [comment]
Now we have this document available at https://gitlab.cee.redhat.com/dtsd/devguide/blob/master/devguide.md#enabling-ike-prow-plugins
