### ISSUE TITLE
WIP prefix configurable

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#28]
Add ability to define custom prefix and label to be used in simple `yaml` file. For the moment we support `WIP`, but people tend to use `[WIP]`, `[WIP]:`, `WIP:`, `DO-NOT-MERGE` etc. We should make it configurable.

**Comment by MatousJobanek** [comment]
I would add the similar prefixes `[WIP]`, `[WIP]:`, `WIP:`, `(WIP)`, `(WIP):` to the default set - match them automatically. But having it configurable is a must!

**Comment by bartoszmajsak** [comment]
Yes, defaults need to be there as we don't want ppl to configure mostly the same things over and over again. So I can think of

- WIP
- DO NOT MERGE
- DON'T MERGE
- WORK-IN-PROGRESS

with all the flavours you listed above (with `:` and `[ ]`, `( )`)

They should be supported by default.
