### ISSUE TITLE
Add probes to plugins

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#62]
Each plugin should provide [readiness and liveness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) (both can point to the same resource)

For this purpose extend the server to respond to HTTP GET `/version` returning plugin name and its version.

**Comment by MatousJobanek** [comment]
closed via https://github.com/arquillian/ike-prow-plugins/pull/128
