### ISSUE TITLE
Bypassing test check should be possible for reviewers but not PR creator

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#73]
Currently, we only allow admins to bypass test verification by using `/ok-without-tests` command in the PR comments. We should enhance this model to cover following use cases

- reviewers should be able to bypass the check too
- PR author shouldn't be able to do that

https://github.com/arquillian/ike-prow-plugins/blob/master/pkg/plugin/test-keeper/plugin/event_handler.go#L91-L99

- [x] create permission service abstracting this logic away from the event handler (open to decide how to deal with roles, e.g. passing as params etc)
- [x] log as `Warn` an attempt to bypass without proper permission
- [x] comment on the issue in such a case saying: `Sorry @handle but you are not allowed to bypass test-keeper check` (optional and to discuss)
- [x] extend test cases (but that should be assumed and will be caught by the plugin here anyway :P)
- [x] update documentation

**Comment by bartoszmajsak** [comment]
In the reference to https://github.com/arquillian/ike-prow-plugins/pull/85#discussion_r179176020

After a long sleep, I think we should not sacrifice improved user experience (comments indicating if something went wrong) vs availability concerns (e.g. API limits) which at this point of time might be premature. Let's think about different path here:

- prevent from duplicated comment
- log API limit reach
- see how `deck` service from Prow infra can be used to list commands to all the plugins configured per repository (this is what [`PluginHelp`](https://github.com/kubernetes/test-infra/blob/8a2e7d1d10b138997830ec18bf4d8bd142355874/prow/pluginhelp/pluginhelp.go#L40) struct is for)
- when we reach a certain threshold of API limit disable some features  (idea to delve further)
- metrics (this needs to be further evaluated)
  - API calls per PR
  - total GH calls per hour (or limit value per hour)
  - anything else we can think of
- evaluate GH  app approach or user sharding (so we can have one user per org instead of alien-ike for all)

WDYT @MatousJobanek. What else can we improve?

**Comment by MatousJobanek** [comment]
Thank you for great ideas. I love all of them and totally agree that we need some more analysis and mainly the metrics. additional logic for disabling some features when we reach a certain threshold would be awesome.

There is another thing I have in my mind - to take a look at `go-github` library if they use some caching mechanism that would reuse older responses and retrieve headers for making conditional requests: https://developer.github.com/v3/#rate-limiting
