### ISSUE TITLE
Expose hook version to OpenShift

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#95]
Similarly to how we expose versions of plugin images, create it for hook too.

  * label for the `Deployment` https://github.com/arquillian/ike-prow-plugins/blob/bab7aa31f1d6710b976a39783d34bf39d4f5484c/cluster/ike-prow-template.yaml#L18-L23
  * environment variable for the container itself
https://github.com/arquillian/ike-prow-plugins/blob/bab7aa31f1d6710b976a39783d34bf39d4f5484c/cluster/ike-prow-template.yaml#L44-L46

Have a look into `Makefile` how those are passed.

**Comment by MatousJobanek** [comment]
@dipak-pawar  it's not yet there, but will be soon https://github.com/arquillian/ike-prow-plugins/pull/114

**Comment by bartoszmajsak** [comment]
@dipak-pawar is it something which blocks your work?
