### ISSUE TITLE
Configure CentosCI builds

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#97]
Similarly to other OSIO projects we should build our images on CentosCI and publish it to `devshift` (we can still keep travis build for the time being due to doc generation).

For reference see [Launcher Backend](https://github.com/fabric8-launcher/launcher-backend/) cico scripts.

Ultimately we have to send PR here https://github.com/openshiftio/openshiftio-cico-jobs

**Comment by MatousJobanek** [comment]
I'm reopening this issue as we need also a script/job for pushing images to devshift.

- [ ] create `cico_build_deploy.sh` that builds the project and deploys docker images to `push.registry.devshift.net`
- [ ] tag every version to enable usage of the "latest" tag (will be default in the templates)
